import/tools/importer/import-compare.html
Adding an option to select different environments.
Test URLs:
- Before: https://main--helix-sportsmagazine--headwirecom.hlx.page/
- After: https://sportsmagazine-poc--helix-sportsmagazine--headwirecom.hlx.page/
=> adding an option to select different environments

blocks/galleryimage/galleryimage.js, scripts/autoblocks.js, scripts/scripts.js, styles/styles.css
Fix #36 
Test URLs:
- Before: https://main--helix-sportsmagazine--headwirecom.hlx.page/import-test/golf-news-tours/_default/gallery/2007/6/samwoods
- After: https://fix-galleryimage--helix-sportsmagazine--headwirecom.hlx.page/import-test/golf-news-tours/_default/gallery/2007/6/samwoods
=> fix galleryimage

blocks/header/header.css, blocks/header/header.html, blocks/header/header.js, blocks/productlisting/productlisting.css, blocks/productlisting/productlisting.js, styles/styles.css
Fix #46 
Test URLs:
- Before: https://v2--helix-sportsmagazine--headwirecom.hlx.page/import-test/play/equipment/products/2022/12/dead-solid-perfect-by-dan-jenkins-1974
- After: https://productlisting--helix-sportsmagazine--headwirecom.hlx.page/import-test/play/equipment/products/2022/12/dead-solid-perfect-by-dan-jenkins-1974
- Original: https://www.golfdigest.com/products/dead-solid-perfect-by-dan-jenkins-1974
=> Productlisting

blocks/footer/footer.css, blocks/footer/footer.js, blocks/header/header.css, blocks/header/header.html, blocks/header/header.js, blocks/header/nav.html, styles/styles.css
Test URLs:
- Before: https://v2--helix-sportsmagazine--headwirecom.hlx.page/import-test/golf-news-tours/features/
- After: https://header-footer-fixes--helix-sportsmagazine--headwirecom.hlx.page/import-test/golf-news-tours/features/
=> header and footer fixes

blocks/header/header.js
Test URLs:
- Before: https://v2--helix-sportsmagazine--headwirecom.hlx.page
- After: https://header-fixes--helix-sportsmagazine--headwirecom.hlx.page
=> header fixes

blocks/gallery-listicle/gallery-listicle.css, blocks/gallery-listicle/gallery-listicle.js, scripts/scripts.js
Test URLs:
- Before: https://v2--helix-sportsmagazine--headwirecom.hlx.page/import-test/play/equipment/apparel/_default/gallery/2020/7/golf-shoes-womens-on-sale
- After: https://gallery-listicle--helix-sportsmagazine--headwirecom.hlx.page/import-test/play/equipment/apparel/_default/gallery/2020/7/golf-shoes-womens-on-sale-freeform
=> Gallery listicle

blocks/embed/embed.css, scripts/scripts.js
Test URLs:
- After: https://ceros-embed--helix-sportsmagazine--headwirecom.hlx.page
=> add ceros embeds

blocks/columns/columns.css, blocks/columns/columns.js
Test URLs:
- After: https://columns--helix-sportsmagazine--headwirecom.hlx.page/
=> Columns Block

blocks/gallery/gallery.css, blocks/gallery/gallery.js
Fix #84 #85 
Test URLs:
- Before: https://main--helix-sportsmagazine--headwirecom.hlx.page/content-v2/archive/_default/gallery/2018/6/photos-holly-sonders
- After: https://fix-gallery--helix-sportsmagazine--headwirecom.hlx.page/content-v2/archive/_default/gallery/2018/6/photos-holly-sonders
=> fix gallery

blocks/product-listing/product-listing.css, blocks/product-listing/product-listing.js
Fix #88, Fix #91, Fix #87 
Test URLs:
- Before: https://main--helix-sportsmagazine--headwirecom.hlx.page/content-v2/play/equipment/products/2022/05/srixon-z-star
- After: https://fix-product-listing--helix-sportsmagazine--headwirecom.hlx.page/content-v2/play/equipment/products/2022/05/srixon-z-star
=> Fix product listing

blocks/product-listing/product-listing.js
Fix #89 
Test URLs:
- Before: https://main--helix-sportsmagazine--headwirecom.hlx.page/content-v2/play/equipment/products/2022/04/ecco-golf-golf-tray-hydromax-water-resistant
- After: https://link-product--helix-sportsmagazine--headwirecom.hlx.page/content-v2/play/equipment/products/2022/04/ecco-golf-golf-tray-hydromax-water-resistant
Different product without URL :  https://link-product--helix-sportsmagazine--headwirecom.hlx.page/content-v2/play/equipment/products/2022/04/bonobos-italian-knit-blazer
=> add URL check

blocks/gallery/gallery.js, scripts/scripts.js
Fix #147 
Test URLs:
- Before: https://main--helix-sportsmagazine--headwirecom.hlx.page/content-v2/play/instruction/_default/gallery/2012/4/photos-aaron-baddeley-2012-04
- After: https://fix-gallery-credits--helix-sportsmagazine--headwirecom.hlx.page/content-v2/play/instruction/_default/gallery/2012/4/photos-aaron-baddeley-2012-04
=> Gallery author and photo credits are mixed

blocks/gallery-listicle/gallery-listicle.css, blocks/gallery-listicle/gallery-listicle.js, scripts/scripts.js, styles/styles.css
Fix #146
Fix #145
Fix #144
Fix #143 
Test URLs:
- Before: https://main--helix-sportsmagazine--headwirecom.hlx.page/content-v2/play/equipment/apparel/_default/gallery/2020/9/winged-foot-gear-us-open
- After: https://fix-gallery-listicle--helix-sportsmagazine--headwirecom.hlx.page/content-v2/play/equipment/apparel/_default/gallery/2020/9/winged-foot-gear-us-open
=> Gallery Listicle fixes

README.md, blocks/default-article/default-article.css, blocks/default-article/default-article.js, blocks/embed/embed.js, blocks/full-bleed/full-bleed.js, blocks/gallery-listicle/gallery-listicle.css, blocks/gallery/gallery.css, blocks/long-form/long-form.js, blocks/open-article/open-article.css, blocks/open-article/open-article.js, scripts/scripts.js
Fix #136
Fix #137
Fix #138
Fix #139
Test URLs:
- Before: https://main--helix-sportsmagazine--headwirecom.hlx.page/content-v2/golf-news-tours/_default/article/2023/7/evian-championship-celine-boutier-leads-yuka-saso-emma-talley-ace
- After: https://fix-default-article--helix-sportsmagazine--headwirecom.hlx.page/content-v2/golf-news-tours/_default/article/2023/7/evian-championship-celine-boutier-leads-yuka-saso-emma-talley-ace
=> Default Article fixes + clean up

blocks/default-article/default-article.css, blocks/default-article/default-article.js, scripts/scripts.js
Fix #142 
Test URLs:
- Before: https://main--helix-sportsmagazine--headwirecom.hlx.page/content-v2/magazine/_default/article/2015/5/my-shot-steve-williams
- After: https://fix-default-portrait--helix-sportsmagazine--headwirecom.hlx.page/content-v2/magazine/_default/article/2015/5/my-shot-steve-williams
=> Default article portrait hero images are not rendered correctly

blocks/header/header.js
Fix #86 
Test URLs:
- Before:  https://main--helix-sportsmagazine--headwirecom.hlx.page/content-v2/archive/_default/gallery/2018/6/photos-holly-sonders
- After: https://fix-header-nav-glitch--helix-sportsmagazine--headwirecom.hlx.page/content-v2/archive/_default/gallery/2018/6/photos-holly-sonders
=> Conditionally display header nav separator

blocks/default-article/default-article.js, blocks/gallery-listicle/gallery-listicle.js, blocks/gallery/gallery.js, blocks/long-form/long-form.css, blocks/long-form/long-form.js, blocks/open-article/open-article.js, scripts/scripts.js, styles/fonts.css
Fix #125 
Fix #126
Fix #127
Fix #129
Fix #130
Test URLs:
- Before: https://main--helix-sportsmagazine--headwirecom.hlx.page/content-v2/the-loop/gambling/article/2023/7/genesis-scottish-open-picks-2023
- After: https://fix-longform--helix-sportsmagazine--headwirecom.hlx.page/content-v2/the-loop/gambling/article/2023/7/genesis-scottish-open-picks-2023
=> Fix longform issues

blocks/hero/hero.js, scripts/scripts.js
Test URLs:
- After: https://fix-landing-pages--helix-sportsmagazine--headwirecom.hlx.page
=> fix landing pages

styles/styles.css
Test URLs:
- After: https://fix-landing-page-bis--helix-sportsmagazine--headwirecom.hlx.page
=> fix landing pages styles

blocks/full-bleed/full-bleed.css, blocks/full-bleed/full-bleed.js, scripts/scripts.js
Fix #104 
Fix #113 
Fix #114 
Fix #115 
Fix #116 
Fix #105 
Fix #111 
Fix #112 
Fix #106 
Fix #122 
Test URLs (104, 113, 114, 115, 116):
- Before: https://main--helix-sportsmagazine--headwirecom.hlx.page/content-v2/golf-news-tours/_default/article/2023/7/british-open-2023-brian-harman-36-hole-lead-what-history-says
- After: https://fullbleed-fixes--helix-sportsmagazine--headwirecom.hlx.page/content-v2/golf-news-tours/_default/article/2023/7/british-open-2023-brian-harman-36-hole-lead-what-history-says
Test URLs (105):
- Before: https://main--helix-sportsmagazine--headwirecom.hlx.page/content-v2/golf-news-tours/_default/article/2023/7/how-historic-would-scottie-scheffler-pga-tour-season-be-with-average-putting-stats
- After: https://fullbleed-fixes--helix-sportsmagazine--headwirecom.hlx.pag …
=> Full bleed page fixes part 1

scripts/scripts.js
Fix #167 
Test URLs:
- After: https://query-limit--helix-sportsmagazine--headwirecom.hlx.page
=> Support reusing cached queries across pages

scripts/scripts.js
Test URLs:
- After: https://fix-block-id--helix-sportsmagazine--headwirecom.hlx.page
=> fix block id gen

blocks/full-bleed/full-bleed.css, blocks/full-bleed/full-bleed.js, scripts/scripts.js
Fix #109 
Fix #102 
Fix #110 
Test URLs:
- Before: https://main--helix-sportsmagazine--headwirecom.hlx.page/content-v2/golf-news-tours/_default/article/2023/7/liv-golf-owgr-delay
- After: https://fix--issues--helix-sportsmagazine--headwirecom.hlx.page/content-v2/golf-news-tours/_default/article/2023/7/liv-golf-owgr-delay
=> Fix  issues

blocks/default-article/default-article.js, scripts/scripts.js
Test URLs:
- Before: https://main--helix-sportsmagazine--headwirecom.hlx.page/content-v2/golf-news-tours/_default/article/2023/1/tom-kim-dunks-approach-shot-asks-fantastic-question-sentry-toc
- After: https://fix-default-article-picture--helix-sportsmagazine--headwirecom.hlx.page/content-v2/golf-news-tours/_default/article/2023/1/tom-kim-dunks-approach-shot-asks-fantastic-question-sentry-toc
=> fix default article optional picture

blocks/embed/embed.js, blocks/full-bleed/full-bleed.css, blocks/full-bleed/full-bleed.js, scripts/scripts.js
Fix #141 
Fix #119 
Test URLs (#119)
- Before: https://main--helix-sportsmagazine--headwirecom.hlx.page/content-v2/golf-news-tours/_default/article/2023/7/british-open-2023-the-most-emotional-moment-of-tiger-woods-career
- After: https://fix-issues--helix-sportsmagazine--headwirecom.hlx.page/content-v2/golf-news-tours/_default/article/2023/7/british-open-2023-the-most-emotional-moment-of-tiger-woods-career
Test URLs (#141)
- Before: https://main--helix-sportsmagazine--headwirecom.hlx.page/
- After: https://fix-issues--helix-sportsmagazine--headwirecom.hlx.page/
=> Fix embed issues

blocks/embed/embed.js
Fix #<gh-issue-id>
Test URLs:
- After: https://fix-embed--helix-sportsmagazine--headwirecom.hlx.page
=> Improve autoplay check to work for all blocks

blocks/default-article/default-article.js, blocks/full-bleed/full-bleed.css, blocks/full-bleed/full-bleed.js, blocks/long-form/long-form.js, blocks/more-cards/more-cards.css, blocks/more-cards/more-cards.js, blocks/open-article/open-article.js, scripts/scripts.js
Fix #108 
Test URLs:
- Before: https://main--helix-sportsmagazine--headwirecom.hlx.page/content-v2/golf-news-tours/_default/article/2023/7/justin-thomas-new-scotty-cameron-counterbalanced-putter-3m-open-fedex-cup-playoffs-ryder-cup
- After: https://feat-more-cards--helix-sportsmagazine--headwirecom.hlx.page/content-v2/golf-news-tours/_default/article/2023/7/justin-thomas-new-scotty-cameron-counterbalanced-putter-3m-open-fedex-cup-playoffs-ryder-cup
- Before: https://main--helix-sportsmagazine--headwirecom.hlx.page/content-v2/the-loop/gambling/article/2023/7/british-open-picks-2023
- After: …
=> Support more cards

404.html, scripts/lib-franklin.js
Fix #117 
https://www.golfdigest.com/404
Test URLs:
- Before: https://main--helix-sportsmagazine--headwirecom.hlx.page/co
- After: https://404-page--helix-sportsmagazine--headwirecom.hlx.page/co
=> Build 404 page

blocks/carousel/carousel.css, blocks/carousel/carousel.js, blocks/footer/footer.css, blocks/header/header.css, blocks/hero/hero.css, blocks/hero/hero.js, helix-query.yaml, styles/styles.css
part of issue https://github.com/headwirecom/helix-sportsmagazine/issues/83
Test URLs:
- Before: https://main--helix-sportsmagazine--headwirecom.hlx.page/video
- After: https://video-landinpage--helix-sportsmagazine--headwirecom.hlx.page/video
=> Video landingpage

blocks/header/header.html, blocks/header/homepage-header.html
Fix #211 
Test URLs:
- Before: https://main--helix-sportsmagazine--headwirecom.hlx.page/content-v2/golf-news-tours/_default/article/2023/7/how-historic-would-scottie-scheffler-pga-tour-season-be-with-average-putting-stats
- After: https://fix-login-signup--helix-sportsmagazine--headwirecom.hlx.page/content-v2/golf-news-tours/_default/article/2023/7/how-historic-would-scottie-scheffler-pga-tour-season-be-with-average-putting-stats
=> Login dialog not working except on homepage

blocks/carousel/carousel.js, blocks/gdplus-subscribe-hero/gdplus-subscribe-hero.css, blocks/gdplus-subscribe-hero/gdplus-subscribe-hero.js
Fix #194 
Test URLs:
- Before: https://main--helix-sportsmagazine--headwirecom.hlx.page/subscribe-golf-digest-plus
- After: https://gdplus-subscribe-page--helix-sportsmagazine--headwirecom.hlx.page/subscribe-golf-digest-plus
=> Gdplus subscribe page

head.html, scripts/scripts.js
Required for #186
Test URLs:
- After: https://feat-vanity-urls--helix-sportsmagazine--headwirecom.hlx.page
=> Support vanity urls

.github/workflows/bulk-import.yaml, bin/bulk-import.js
=> add vanity url bulk import gh action

head.html
Test URLs:
- After: https://fix-sitename--helix-sportsmagazine--headwirecom.hlx.page
=> add sitename

import/tools/importer/import.mjs
Fix #13
Test URLs:
- Before: https://main--helix-sportsmagazine--headwirecom.hlx.page/content-v2/golf-news-tours/_default/article/2023/7/3m-open-lee-hodges-wins-big-lead-sets-up-fedex-cup-playoffs
- After: https://main--helix-sportsmagazine--headwirecom.hlx.page/content-v2/golf-news-tours/_default/article/2023/7/3m-open-lee-hodges-wins-big-lead-sets-up-fedex-cup-playoffs
=> Fix all images - import org rendition, set alt and title.

blocks/cards/cards.js, blocks/carousel/carousel.js, blocks/gdplus-subscribe-hero/gdplus-subscribe-hero.js, blocks/hero/hero.js, scripts/scripts.js
Adjusted window.store fetch & cache system so blocks with the same queries do not show duplicate articles.
Adjusted query limits to allow for dynamic limits based on block variations.
Partial Fix #185
Test URLs:
- Before: https://main--helix-sportsmagazine--headwirecom.hlx.page/golf-news-tours/features
- After: https://duplicate-query-fixes--helix-sportsmagazine--headwirecom.hlx.page/golf-news-tours/features
=> Duplicate query fixes

blocks/embed/embed.css, blocks/embed/embed.js
Fix #239 
Test URLs:
- After: https://iframe-early-load--helix-sportsmagazine--headwirecom.hlx.page
=> Loading iframes earlier

import/tools/importer/import.mjs
Fix #255
Test URLs:
- Before: https://main--helix-sportsmagazine--headwirecom.hlx.page/content-v2/play/courses/_default/article/2022/12/national-golf-links-of-america-every-hole-drone
- After: https://main--helix-sportsmagazine--headwirecom.hlx.page/content-v3/courses/default/article/2022/12/national-golf-links-of-america-every-hole-drone
Google Documents: 
- Before: https://docs.google.com/document/d/1_SgLikPsL1qcKCpTrspzBaRUWZ1yPaqPOR44qYwuQjU/edit
- After: https://docs.google.com/document/d/1zsDe6TVQs9InC9PpUeqA5Em4tkNqyAuzthc0CjnOsaA/edit
=> Issue 255 - video embed title and description are not imported
